## This functions calculate the inverse of a matrix and store the result
## in a cache object, so it only needs to calculate the result once.

## makeCacheMatrix() creates a list which stores the original matrix and
## sets the enviroment where the cache object "inv" is defined.

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        setinverse <- function (inverse) inv <<- inverse
        getinverse <- function () inv
        invisible(list("get"=x, "setinverse"=setinverse, "getinverse"=getinverse                                                                                ))
}


## First time you call cacheSolve() on an certain object, it will use the
## list generated by makeCacheMatrix() in order to calculate the inverse matrix
## and set it into the cache object.
## After that, instead of calculate it again it will retrieve the value from the
## cache object.

cacheSolve <- function(x, ...) {
        inv <- x$getinverse()
        if(!is.null(inv)) {
                message("Getting cached data.")
                return(inv)
        }
        matriz <- x$get
        inv <- solve(matriz)
        x$setinverse(inv)
        inv
}
